kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    deployment.kubernetes.io/revision: '1'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"imageclassifierkalptree:latest","namespace":"cc-uc-other-industrial-oracle-team-c"},"fieldPath":"spec.template.spec.containers[?(@.name==\"imageclassifierkalptree\")].image"}]
    openshift.io/generated-by: OpenShiftWebConsole
  selfLink: >-
    /apis/apps/v1/namespaces/cc-uc-other-industrial-oracle-team-c/deployments/imageclassifierkalptree
  resourceVersion: '19373189'
  name: imageclassifierkalptree
  uid: d7d381ad-f0a7-4084-aca7-52317decf1a7
  creationTimestamp: '2020-06-09T01:30:15Z'
  generation: 10
  namespace: cc-uc-other-industrial-oracle-team-c
  labels:
    app: imageclassifierkalptree
    app.kubernetes.io/component: imageclassifierkalptree
    app.kubernetes.io/instance: imageclassifierkalptree
    app.kubernetes.io/part-of: imageclassifier-app-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imageclassifierkalptree
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: imageclassifierkalptree
        deploymentconfig: imageclassifierkalptree
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: imageclassifier
          emptyDir: {}
      containers:
        - name: imageclassifierkalptree
          image: 'docker.io/dibbog/imageclassifier:1.2'
          ports:
            - containerPort: 5000
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 80m
              memory: 120Mi
            requests:
              cpu: 25m
              memory: 40Mi
          volumeMounts:
            - name: imageclassifier
              mountPath: /src/kaplptreeimages/uploads
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 10
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2020-06-09T07:36:37Z'
      lastTransitionTime: '2020-06-09T07:36:37Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2020-06-09T07:36:37Z'
      lastTransitionTime: '2020-06-09T07:06:52Z'
      reason: NewReplicaSetAvailable
      message: >-
        ReplicaSet "imageclassifierkalptree-779b6c6d74" has successfully
        progressed.
